name: gems-cpp-extension

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.py'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.hpp'
      - '**.cc'
      - 'CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.mk'
      - 'Makefile'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.py'
      - '**.cpp'
      - '**.cu'
      - '**.h'
      - '**.hpp'
      - '**.cc'
      - 'CMakeLists.txt'
      - '**/*.cmake'
      - '**/*.mk'
      - 'Makefile'

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-experimental-only.yaml

  experimental-noop:
    needs: detect-changes
    if: needs.detect-changes.outputs.run_ci != 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipping CI experimental_ops only"

  build-C-extension:
    needs: detect-changes
    if: needs.detect-changes.outputs.run_ci == 'true'
    runs-on: cpp

    steps:
      - uses: actions/checkout@v4

      - name: Build FlagGems with C-extension
        shell: bash
        run: |
          SKBUILD_CMAKE_ARGS="-DFLAGGEMS_BUILD_C_EXTENSIONS=ON" pip install --no-build-isolation -v -e .

      - name: Run FlagGems CTests
        shell: bash
        run: |
          cd build/cpython-311/ctests
          export FLAGGEMS_SOURCE_DIR=$(python -c "import os;import flag_gems;print(os.path.dirname(flag_gems.__file__))")
          ctest -V
